PLAT-71246 - Relationships guide [REVIEW]
adobe/reactor-developer-docs pull request #99
Opened 2020-11-02 23:10 UTC by pnolan89

https://jira.corp.adobe.com/browse/PLAT-71246

2020-11-03 18:04 UTC, carlojavier submitted a review, later dismissed
LGTM!

2020-11-13 21:11 UTC, thebenrob requested changes
I think we should add some links to appropriate API specs in a few places.

The other thing I think we should do is add information about the format of the required payloads.  This could be either here in this guide (centralized in one place) or we could add it to the individual API spec pages that we link to - though if we go that route, we'll need to add the same info to other pages also.

For the Create by URL scenarios, I think we should say that inside the "data" object, you provide a "relationships" object.  That relationships object has another object that defines the relationship type you want to add ("extension" for example), then inside that a "data" object with an ID and a type.

It would also be worth specifying in whether you can add more than one a time.  Data elements for example only have one relationship, but Rule Components have two, and you have to specify both.

Create by URL - In these scenarios, you provide the "data" object, and then an array of objects inside it.  Each object needs to specify an "id" and a "type".  But you can add as many rules, data elements, and extensions as you want in a single call.

Now that I'm thinking about it, we should probably also say somewhere what the acceptable values of "type" are, which are: "data_elements", "rules", "extensions", and "environments".

2020-11-13 21:11 UTC, thebenrob commented on api/guides/relationships.md
> +  * Create a `data_element` with the required `extensions`
Can we link to the appropriate docs here: /api/reference/1.0/data_elements/create/

2020-11-13 21:11 UTC, thebenrob commented on api/guides/relationships.md
> +  * Create an `environment` with the required `host` relationship.
Link to /api/reference/1.0/environments/create/

2020-11-13 21:11 UTC, thebenrob commented on api/guides/relationships.md
> +  * Creating a relationship between a library and an environment: `/libraries/{LIBRARY_ID}/relationships/environment`
Link to http://localhost:8000/api/reference/1.0/libraries/relationships/environment/set_relationship/

2020-11-13 21:11 UTC, thebenrob commented on api/guides/relationships.md
> +  * Creating a relationship between a library and a rule: `/libraries/{LIBRARY_ID}/relationships/rules`
Link to http://localhost:8000/api/reference/1.0/libraries/relationships/rules/add_relationships/

2020-11-17 16:39 UTC, thebenrob submitted a review, later dismissed
This is beautiful =)

2020-11-17 17:23 UTC, thebenrob approved these changes

2020-11-17 17:28 UTC, merged